### ISSUE TITLE
Desna's Shooting Star still not appearing

### ISSUE THREAD

**Issue by DuhHamletovogOca** [YLMstring/Prestige-Plus#37]
Hi, I know one of the releases had the fix for the feat not appearing, but for me it's still not there, only the default CO+ ones. What are the requirements for this feat to show up? Just DFT from CO+ or is there something else? I didn't notice anything in Prestige Plus settings regarding this feat.

**Comment by DuhHamletovogOca** [comment]
Yes, I'm on the latest version. I made sure DFT itself works with Seelah.

**Comment by YLMstring** [comment]
![image](https://github.com/YLMstring/Prestige-Plus/assets/61271096/42a779ad-c6b0-4995-b633-940975a54f19)
Works on my machine :p

**Comment by DuhHamletovogOca** [comment]
![image](https://github.com/YLMstring/Prestige-Plus/assets/157995279/dde5c551-c685-4e83-a5bb-27a9ab34af34)

Still not showing up for me. I probably have a conflict. Is there something in Prestige Plus settings that need to be turned on?

Tried in Toybox as well, it's not showing up in Features.

**Comment by YLMstring** [comment]
Guided Hand lol
