### ISSUE TITLE
Zen Archer "Way of the Bow - Longbow" gives Weapon Focus in Longsword instead of Longbow

### ISSUE THREAD

**Issue by PawelS-AoW** [YLMstring/Prestige-Plus#38]
Mod version: 3.0.7
Also reported on Nexus [here](https://www.nexusmods.com/pathfinderwrathoftherighteous/mods/552?tab=bugs).

If you level up a Zen Archer to level 2 and choose Longbow for Way of the Bow, you will get a weapon focus in Longsword instead.

I think it's caused by the Divine Marksman archetype, who gets "Iomedae Influence", which is created as a copy of the Zen Archer's "Way of the Bow - Longbow", with Longbow changed to Longsword. Somehow the weapon gets changed in the original version of the class feature.

Disabling the Divine Marksman archetype in Mod Menu prevents the bug from happening.

**Comment by YLMstring** [comment]
shoot, it's a soft copy
will fix in v3.0.8!
