### ISSUE TITLE
Spells per day not working for first prestige level

### ISSUE THREAD

**Issue by alkdnvwoeivn** [YLMstring/Prestige-Plus#39]
The description makes it sound like prestige classes with "spells per day" continue spellcasting from a previous class, but it skips the first level. For example, my 5th-level eldritch archer took a level in hinterlander at level 6, but his caster level is still 5 and he didn't get to pick any new spells. Same thing happened when I did cleric to dawnflower anchorite. On the second prestige level spellcasting resumes, but that first level is still lost. Is this a bug or am I reading the description wrong?

**Comment by YLMstring** [comment]
It's intended :p
They skip a level on tabletop too

**Comment by alkdnvwoeivn** [comment]
Oh, ok. I guess I'm used to Loremaster in the base game which doesn't skip a level (or maybe it does and one of my mods changes it?). I really love the idea of prestige classes, but you have to give up so much (especially with the TTT capstones) it's hard to justify using them. Skipping a spellcasting level just makes it that much harder to justify.
