### ISSUE TITLE
How RhinoCharge works

### ISSUE THREAD

**Issue by Valhally** [YLMstring/Prestige-Plus#40]
Hello!
I'm a beginner and I am reading your code but I don't understand how RhinoCharge works.I see that RhinoChargeAbility just adds the RhinoChargeBuff to the character, but it's not clear how it allows the character to initiate a charge.

(I'm not sure if it's appropriate to post the question here, and if it isn't, I'm very sorry)

**Comment by Valhally** [comment]
Oh I think I got it, the logic is in the GiganticAssaultController

**Comment by YLMstring** [comment]
sorry for not writing comments :p
