### ISSUE TITLE
Umbral Agent Grapple

### ISSUE THREAD

**Issue by TequilaSunsetIRL** [YLMstring/Prestige-Plus#42]
So the Grasping Darkness progression of Shadow Chains still allows for a reflex safe even with the Grasping Darkness passive ability toggled on. The reflex safe itself is difficult to raise the DC of so that makes it a pretty unlikely move to ever pull off at the level we gain access to it.

And also, thank you for making this mod. You chose really cool classes to add to the game and making the grapple system work the way you did was really smart. Good work 👍

**Comment by YLMstring** [comment]
Just asked paizo people, they said there's no saving throw! Awesome

**Comment by TequilaSunsetIRL** [comment]
Sorry, I think I worded that wrong. I meant your mod is allowing a saving throw when it shouldn't. Here I'll try adding a screenshot of it happening in combat. 

![Wrath 2024-05-26 12-13-00](https://github.com/YLMstring/Prestige-Plus/assets/67348653/f076e130-beba-4267-93bc-da829c79aa8f)

**Comment by YLMstring** [comment]
Yeah I know, gonna fix this today :p

**Comment by YLMstring** [comment]
It shall make the class great again!

**Comment by YLMstring** [comment]
Fixed in 3.1.5!

**Comment by TequilaSunsetIRL** [comment]
Sweeeet looking forward to it! I never realized this class' potential for shenanigans grappling at range until you released Prestige Plus. Cheers:)
