### ISSUE TITLE
Currently incompatible with ExpandedContent

### ISSUE THREAD

**Issue by AlistairKion** [YLMstring/Prestige-Plus#46]
Having tested my mod list extensively, I get the following error if I try to launch with ExpandedContent, TabletopTweaks-Core, ModMenu, and Prestige-Plus:

[328,8391 - Unity]: NullReferenceException: Object reference not set to an instance of an object
ExpandedContent.Config.ModSupport+BlueprintsCache_Init_Patch.Postfix () (at <9626326838bd4569944bea6013e857d1>:0)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Kingmaker.Blueprints.JsonSystem.BlueprintsCache.Init_Patch207(Kingmaker.Blueprints.JsonSystem.BlueprintsCache)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Kingmaker.Blueprints.JsonSystem.StartGameLoader.LoadPackTOC_Patch11(Kingmaker.Blueprints.JsonSystem.StartGameLoader)
Kingmaker.GameStarter+d__28.MoveNext () (at <95842a8b72b4464786c5ce2630f0c9e5>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext () (at <4fae2288737c4dfda349689bbefabfcc>:0)

The error does not occur if you only have either ExpandedContent or Prestige-Plus, rather than both.

I suspect this lies more on ExpandedContent's side of things, given the error, but the error only occurs if this mod is also installed, so I thought I'd mention it here too.

**Comment by YLMstring** [comment]
My mod breaks!
I can fix it once BPCore (the mod framework) is updated

**Comment by YLMstring** [comment]
v3.2.0 should fix it
