### ISSUE TITLE
Majority of Classes + Feats not showing up

### ISSUE THREAD

**Issue by Gyrados15** [YLMstring/Prestige-Plus#48]
First thanks for the Update :) I can run the game again with this and the Expanded content without it hanging.

For some weird reason though I'm only seeing Heritor Knight and Ramizan Priest classes, and feats eg 
Black Seraph isn't showing up (Toy box screenshot and Gamelog Full attached)

![image](https://github.com/YLMstring/Prestige-Plus/assets/129967365/fa71c8a6-f6a9-4aa6-9be2-d8a7029a6de7)
[GameLogFull.txt](https://github.com/user-attachments/files/15846012/GameLogFull.txt)

**Comment by YLMstring** [comment]
Do you turn PP on?
There isn't a single pp log in the file

**Comment by Gyrados15** [comment]
I'm just going to crawl into a Hole and Die of embarrassment now...

**Comment by YLMstring** [comment]
lol
