### ISSUE TITLE
Sinuous Daggerplay

### ISSUE THREAD

**Issue by Kosha99** [YLMstring/Prestige-Plus#51]
![Screenshot_5](https://github.com/YLMstring/Prestige-Plus/assets/159198610/0ada6553-2ac3-40fc-b12b-ba65e83e6715)
How this ability work? Is it suppose to be additional tail attack or do I need equip dagger like for Kasatha?

**Comment by YLMstring** [comment]
I just half ass it :p
It's like flurry of blows (for daggers)

**Comment by YLMstring** [comment]
Hmmm, could give it some more love

**Comment by YLMstring** [comment]
Should be somewhat appealing now!
