### ISSUE TITLE
Guided Hand with Atheism

### ISSUE THREAD

**Issue by Lordmitch2** [YLMstring/Prestige-Plus#55]
Guided Hand can be chosen if you have Atheism which has no favored weapon. Guided Hand should not be able to be chosen on a character with Atheism.   
![image](https://github.com/YLMstring/Prestige-Plus/assets/47829580/055afb75-3578-4320-a961-501d3984928f)

**Comment by YLMstring** [comment]
make sense1

**Comment by Lordmitch2** [comment]
As an Oracle you can get the channel energy feature and Selective Channel, which will allow you to pick Guided Hand.  As an Oracle you can chose Atheism and have no god and no favored weapon, this would make Guided Hand useless for that character. I noticed it when levelling up Daeran, he could pick Guided Hand but he has no god and thus no favored weapon. This is not a major issue as you can just not pick it but I thought I would mention it and that it would be a good idea to prevent a character with Atheism from choosing this feat.

**Comment by YLMstring** [comment]
Yeah small fix, I'll do it along with the next patch

**Comment by YLMstring** [comment]
Fixed！
