### ISSUE TITLE
Forest Warden Bonus Feat broken

### ISSUE THREAD

**Issue by Ebonmark** [YLMstring/Prestige-Plus#56]
![FW](https://github.com/YLMstring/Prestige-Plus/assets/90540615/53cbed4a-f4b5-4baf-9d6d-e2bee273ec53)

The bonus feat selection screen for Forest Warden doesn't seem to work properly. It doesn't register any selections.

BTW thanks so much for this mod! It has really grown a lot since I last checked it out and I consider it a staple now.

**Comment by YLMstring** [comment]
which aligned class do you take?

**Comment by YLMstring** [comment]
Also send me GameLogFull.txt plz
(after you clicking that feat for a few times)

**Comment by YLMstring** [comment]
Probably toybox issues

**Comment by Ebonmark** [comment]
[GameLogFull.txt](https://github.com/user-attachments/files/16021930/GameLogFull.txt)
Here ya go. I started the game up, tried to take second level Forest Warden with Seelah and click the feats a few time and then closed the game. I tried with both a Sorcerer and a Paladin and both have the same issue.

**Comment by Ebonmark** [comment]
Its weird. If I switch Toybox off midgame and try to level up it still wont let me take a feat and move forward with Forest Warden. If I turn toybox off, exit the game and reload my game is all sorts of fucked up lol - guess toybox wrote some stuff to the save and the save becomes dependent on it.
