### ISSUE TITLE
dragon fury's fury training cannot add drunken master's ki pool

### ISSUE THREAD

**Issue by hyfshadow** [YLMstring/Prestige-Plus#57]
dragon fury's fury training cannot add drunken master's ki pool, also Spear Dancing Spiral cannot be used on some archetypes' Flurry of Blows when those changed the initial Flurry of Blows

**Comment by YLMstring** [comment]
which archetype?

**Comment by hyfshadow** [comment]
my bad.i tested it again, and it seems that there's no problem with the spear dancing spiral.sry

**Comment by YLMstring** [comment]
Simply don't unequip :p
Drunken master's ki works for me, we'll see if others have the same issue

**Comment by YLMstring** [comment]
Fury training's behavior is not consisitant, sometimes it gives more but it should never give less

**Comment by hyfshadow** [comment]
my bad.fury training works for me too.thanks for your reply and thanks for your mod :-)
