### ISSUE TITLE
Arsenal chaplain cannot take TTT's mythic abilities about blessing

### ISSUE THREAD

**Issue by nextentlligods** [YLMstring/Prestige-Plus#60]
These include Abundant Blessing, Enhanced Blessings and Impossible Blessing. 
BTW, there is also a localization problem: in arsenal chaplain's lv 19 war blessing feature
"16级起，随军神父的战争祝福费用再减少1点。" It should be 19 instead of 16.
And if you have time, perhaps you can take Holic's code in CtoW as reference to make this archetype more tabletop-like:
[https://github.com/Holic75/KingmakerRebalance/blob/master/CallOfTheWild/Classes/Warpriest.cs](url)
it's really wierd to buff war blessing multiple times to all party numbers at lv19, can you make it an AOE ablity?

**Comment by YLMstring** [comment]
躺平。jpg
那是1个吗，那是足足5个（绝望
可以用泡泡buff一键上，假装是aoe就好了

**Comment by YLMstring** [comment]
另外毛子把战争祝福村成迅捷了，所以按桌面这个变体就没意义了，我直接村爆

**Comment by nextentlligods** [comment]
好吧，那大佬可以把TTT里面有关祝福神话能力的前置给加上吗？

**Comment by YLMstring** [comment]
修好叻

**Comment by nextentlligods** [comment]
多谢大佬。。
