### ISSUE TITLE
The mod integration with Expanded Content no longer works

### ISSUE THREAD

**Issue by force200** [YLMstring/Prestige-Plus#61]
The game refuses to load when both Prestige Plus and Expanded Content are installed.

**Comment by force200** [comment]
> Version? Does the log complain?

The newest ones for the mods and UMM, 2.3.2c for the game. I don't know about a log, the game just stops loading after about 2/3 of the loading bar after I start it and just sits there. Doesn't even get shown as "not responding" in the Task Manager.

**Comment by YLMstring** [comment]
I mean mod version lol
Both pp and ec need to be up-to-date
Pretty sure it's fine 'cause I'm playing with both tonight

**Comment by YLMstring** [comment]
Log is in C:\Users\your name\AppData\LocalLow\Owlcat Games\Pathfinder Wrath Of The Righteous, send the full log

**Comment by YLMstring** [comment]
Also if you turn TTT-base fixes off, EC might complain or even affect compatibility with PP

**Comment by force200** [comment]
I just double-checked everything and noticed that it was a screw up on my part. I messed up something with UMM, so that the update for prestige plus didn't install properly and I was still running an oder version. I re-installed the latest version and everything started working again.
