### ISSUE TITLE
NPC failed grapple escape does not use action in turn-based mode

### ISSUE THREAD

**Issue by dametdame** [YLMstring/Prestige-Plus#62]
Screenshot attached. 
![b147319dbcdd73658b0e1211cc7f468b](https://github.com/user-attachments/assets/96dd519e-d45e-4f02-8b7c-7ea6c195b2c8)

When enemy NPCs fail to escape a grapple (either with grapple or trickery), they still get an attack (maybe other standard or full round actions too? Unsure) in turn-based mode. Interestingly, this does not apply if they succeed in the escape. It also does not apply outside of turn-based mode, where it seems to work as expected (NPCs do nothing if they fail to escape). I've tested it a decent number of times.

I guess another way of viewing it is that NPCs are getting a free attempt to escape grapple whenever they attack; not sure how it's implemented.

Initially saw it with quite a lot of mods enabled, but tried it with just TTT core and base, mod menu, and this mod enabled and same result. I am inclined to think that not a lot of people have used grapple in turn-based mode. Unfair difficulty, drunken master monk with Grapple feat.

**Comment by dametdame** [comment]
Another screenshot with just the 4 mods described above enabled.
![test2](https://github.com/user-attachments/assets/c347b8fc-0705-4630-a0cf-d06849082678)

**Comment by YLMstring** [comment]
This is intended
A DM can decide if the monster will try breaking free or not, but there's no DM
So basically if the monster fail, it will load an earlier save :p
