### ISSUE TITLE
v3.4.5 update

### ISSUE THREAD

**Issue by Noxis-source** [YLMstring/Prestige-Plus#63]
Hi
Just updated v3.4.4 > v3.4.5
Saves that depend on the mod cannot be loaded because the game thinks a DLC is missing

**Comment by YLMstring** [comment]
hmm, I don't think my mod can cause this
Try rolling back to 3.4.4?

**Comment by Noxis-source** [comment]
Yeah, I did, works this way

**Comment by Noxis-source** [comment]
@YLMstring Sorry to bother you, but did you have a chance to look into what might be happening? I'm fine with finishing my current run without updates, only wish to confirm that everything works as expected

**Comment by YLMstring** [comment]
Yes, I'm playing the game as my 3rd playthru, works on my machine lol
We'll see if others have this issue

**Comment by YLMstring** [comment]
consider verifying your game file if you do have the dlc the game thinks you're missing

**Comment by Noxis-source** [comment]
I did :)
It doesn't say which one is missing, like a mod was uninstalled mid playthrough
Oh well, whatever :)

**Comment by YLMstring** [comment]
It is a specific blueprint that is missing then? If it is, then it's probably shadowdancer stuff, I remove some blueprints in 3.4.5, toybox can help you load with missing blueprints iirc
