### ISSUE TITLE
[Bug] White-Haired Witch Reach

### ISSUE THREAD

**Issue by ZeliasC** [YLMstring/Prestige-Plus#66]
When the witch increase her hair reach, all her other attacks increase in reach too. As a full round action, she can do all her attacks at 30ft, including any other natural attack she gets, and then do her grapple with her gore attack. 

This can be somewhat mitigated by using the standard action 'Hair Attack' the witch gains, which do not consider all her iterative attacks and only attack with her hair.

Edit: I haven't tried how this interact with spells like Long Arm and any other similar features that increase reach.

**Comment by YLMstring** [comment]
Consider it a buff to the class, you can wield stuff with your hair, tian-xia style, eh?
Theoretically I can increase hair's reach only, but that breaks owlcat's distance pridiction, the game doesn't know if you want to attack with hair only from afar or to get closer still

**Comment by JamesKrolak** [comment]
This also kind of makes up for things like the Hair can't be used with Feral Combat Training (from another mod) to Flurry.  (at least, I assume it would be super hard to figure out how to get around the way owlcat coded full attacks to work)
