### ISSUE TITLE
Feature Request: Umbral Dragon Bloodline (Sorcerer) 

### ISSUE THREAD

**Issue by jackpotzero** [YLMstring/Prestige-Plus#69]
vanilla dragon bloodline but Negative Energy 
[Expanded Content](https://github.com/ka-dyn/ExpandedContent) has the umbral dragon transformation/Breath weapon  (9th lvl spell: "Form of the Exotic Dragon")

**Comment by YLMstring** [comment]
not on tabletop?

**Comment by YLMstring** [comment]
(owlcat suspecting)
