### ISSUE TITLE
Request - Add Pharasma to Deific Obedience list

### ISSUE THREAD

**Issue by Ardencroft** [YLMstring/Prestige-Plus#74]
Just wanted to know if you could add Pharasma to the deific obedience list (any of the boons you feel like putting in would work, just think it would fit really well with the Aeon mythic path and the daggers bonus from the base obedience is strong too

**Comment by YLMstring** [comment]
More obedience incoming……
![image](https://github.com/user-attachments/assets/8e693fc2-7f7f-422a-b4b0-ce694126ddfb)

**Comment by YLMstring** [comment]
tada!
