### ISSUE TITLE
3.6.6 has CTD issue with Expanded Content

### ISSUE THREAD

**Issue by abishai** [YLMstring/Prestige-Plus#80]
After update to 3.6.6 I've discovered CTD when I hit exit button. Rollback to 3.6.5 fixes it.
To reproduce,
1. Load the game with Prestige+ and Expanded content active (and necessary requirements)
2. Hit Exit Button.

The game will crash. I'll try to investigate if there is a togglable option that conflicts.

**Comment by YLMstring** [comment]
I'll investigate, actually I encounter this too when testing
but CTD when exiting is not really a CTD lol

**Comment by abishai** [comment]
True, but I was scared to load a save in case this is a sign of more serious issue :p

**Comment by Mythalar** [comment]
Hey, it seems there is also an issue with Isekai mod (kind of updated version from @evandixon [here](url=https://github.com/JohN100x1/IsekaiMod/issues/199).
If both Prestige Plus and Isekai are enabled then the game is stuck loading, if one is disabled then no prob (hence the CTD on exit with Expanded Content).

I had no issue so far with both mods and all my saves cannot be loaded then :'(
[GameLogFull.txt](https://github.com/user-attachments/files/17006489/GameLogFull.txt)

**Comment by evandixon** [comment]
Just skimming that log, I wonder if the IDs of the blueprints both mods add are conflicting? IDs added by the Isekai mod in case anyone wants to compare with this or expanded content: https://github.com/JohN100x1/IsekaiMod/blob/master/IsekaiMod/Config/Blueprints.json

**Comment by YLMstring** [comment]
hopefully fixed in v3.6.7!

**Comment by Mythalar** [comment]
All good on my side !
