### ISSUE TITLE
Feature request: Shelyn obedience prerequisite

### ISSUE THREAD

**Issue by Kosha99** [YLMstring/Prestige-Plus#83]
Can you add smite evil as alternative prerequisite for Shelyn obedience so that Seelah can take it and you don't have to use merc paladin?

**Comment by YLMstring** [comment]
![5dv9wz](https://github.com/user-attachments/assets/a472ba95-2602-4ba0-8707-52946635a843)
We have smite evil obedience at home

**Comment by YLMstring** [comment]
though there are feats that let you change alignment on tt, we might have it someday if I'm not lazy
