### ISSUE TITLE
Lesser Spell Synthesis bug

### ISSUE THREAD

**Issue by Kosha99** [YLMstring/Prestige-Plus#84]
Activation of ability ends turn in turn-based mode and so I can't cast double spell.

**Comment by Kosha99** [comment]
With activated Coloxus aspect move action activation works normally but standart action ends turn.

**Comment by YLMstring** [comment]
It's because of some owlcat settings, ends your turn if you lost sdandard action or something, turn it off :p

**Comment by Kosha99** [comment]
Everything works now. Thanks for help.
