### ISSUE TITLE
Magus can't use spellstrike / spell combat on swarms with this mod on. Also, grappled magi keep trying to cast unsuccessfully.

### ISSUE THREAD

**Issue by usernameisnotavailable123** [YLMstring/Prestige-Plus#85]
Tried with toybox (to spawn rats), TTT, and this mod. Is this a bug or is there a setting for this?

**Comment by YLMstring** [comment]
Will fix the former in next patch
The latter is because being grappled gives you spell failure chance :p

**Comment by usernameisnotavailable123** [comment]
They didn't stop after one failure. They just keep trying, softlocking my game in turn-based mode. Is that related to this mod too?

**Comment by YLMstring** [comment]
Sounds like mystical mayhem...

**Comment by YLMstring** [comment]
If ya don't have mystical mayhem send full log when softlocking plz

**Comment by YLMstring** [comment]
Fixed!
